---
- name: Variables from prompt
  hosts: localhost
  connection: local

  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false

  tasks:
    - name: Print credentials
      ansible.builtin.debug:
        msg: "Hello, username is: {{ username }}"
