---
- name: Vars preference demo
  hosts: localhost
  connection: local

  vars:
    person_name: from play level

  # vars_files:
  #   - course.yaml

  vars_prompt:
    - name: person_name
      prompt: What is your name?
      private: false

  tasks:
    - name: From task level
      # vars:
      #   person_name: from task level
      ansible.builtin.debug:
        msg: "Name: {{ person_name }}"

        #1. args or command line
        #2. from prompt
        #3. files
        #4. prompt

