- name: check the facts
  hosts: local
  connection: local
  become: yes

  tasks:
    - name: install nginx if RedHat
      ansible.builtin.dnf:
        name: nginx
        state: latest
      when: ansible_os_family == "RedHat"  # use ansible_ while referring to facts

    - name: install nginx if Debian
      ansible.builtin.apt:
        name: nginx
        state: latest
      when: ansible_os_family == "Debian"
