- - name: Install packages
  hosts: local
  connection: local
  become: yes  # needed to install packages

  tasks:
    - name: install or remove packages based on loop values
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: "nginx", state: "absent" }
        - { name: "mysql", state: "absent" }
        - { name: "zip", state: "latest" }
